// objects.h:422-730 a_can values. Unlisted armor has no magic cancellation.
export const ARMOR_MAGIC_NEGATION = {
    cornuthaum: 1,
    'plate mail': 2,
    'crystal plate mail': 2,
    'bronze plate mail': 1,
    'splint mail': 1,
    'banded mail': 1,
    'dwarvish mithril-coat': 2,
    'elven mithril-coat': 2,
    'chain mail': 1,
    'orcish chain mail': 1,
    'scale mail': 1,
    'studded leather armor': 1,
    'ring mail': 1,
    'orcish ring mail': 1,
    'leather armor': 1,
    'mummy wrapping': 1,
    'elven cloak': 1,
    'orcish cloak': 1,
    'dwarvish cloak': 1,
    'oilskin cloak': 2,
    robe: 2,
    'alchemy smock': 1,
    'leather cloak': 1,
    'cloak of protection': 3,
    'cloak of invisibility': 1,
    'cloak of magic resistance': 1,
    'cloak of displacement': 1,
};

// objects.h: armor AC contributions (10 minus the listed armor class).
export const ARMOR_AC_BONUS = {
    'cloak of magic resistance': 1,
    'cloak of displacement': 1,
    'cloak of invisibility': 1,
    'cloak of protection': 3,
    'mummy wrapping': 0,
    'elven cloak': 1,
    'orcish cloak': 0,
    'dwarvish cloak': 0,
    'alchemy smock': 1,
    'leather cloak': 1,
    'oilskin cloak': 1,
    robe: 2,
    'leather jacket': 1,
    'leather armor': 2,
    'ring mail': 3,
    'orcish ring mail': 2,
    'scale mail': 4,
    'orcish chain mail': 4,
    'chain mail': 5,
    'gray dragon scale mail': 9,
    'gold dragon scale mail': 9,
    'silver dragon scale mail': 9,
    'red dragon scale mail': 9,
    'white dragon scale mail': 9,
    'orange dragon scale mail': 9,
    'black dragon scale mail': 9,
    'blue dragon scale mail': 9,
    'green dragon scale mail': 9,
    'yellow dragon scale mail': 9,
    'gray dragon scales': 3,
    'gold dragon scales': 3,
    'silver dragon scales': 3,
    'red dragon scales': 3,
    'white dragon scales': 3,
    'orange dragon scales': 3,
    'black dragon scales': 3,
    'blue dragon scales': 3,
    'green dragon scales': 3,
    'yellow dragon scales': 3,
    'studded leather armor': 3,
    'banded mail': 6,
    'splint mail': 6,
    'dwarvish mithril-coat': 6,
    'elven mithril-coat': 5,
    'plate mail': 7,
    'crystal plate mail': 7,
    'bronze plate mail': 6,
    helmet: 1,
    'orcish helm': 1,
    'elven leather helm': 1,
    'dwarvish iron helm': 2,
    fedora: 0,
    cornuthaum: 0,
    'dunce cap': 0,
    'dented pot': 1,
    'helm of brilliance': 1,
    'helm of caution': 1,
    'helm of opposite alignment': 1,
    'helm of telepathy': 1,
    'small shield': 1,
    'large shield': 2,
    'elven shield': 2,
    'orcish shield': 1,
    'Uruk-hai shield': 1,
    'uruk-hai shield': 1,
    'shield of drain resistance': 1,
    'shield of shock resistance': 1,
    'dwarvish roundshield': 2,
    'shield of reflection': 2,
    'leather gloves': 1,
    'gauntlets of fumbling': 1,
    'gauntlets of power': 1,
    'gauntlets of dexterity': 1,
    'low boots': 1,
    'iron shoes': 2,
    'high boots': 2,
    'speed boots': 1,
    'water walking boots': 1,
    'jumping boots': 1,
    'elven boots': 1,
    'kicking boots': 1,
    'fumble boots': 1,
    'levitation boots': 1,
    'hawaiian shirt': 0,
    't-shirt': 0,
};

// include/hack.h:ARM_BONUS: erosion removes base armor, never enchantment.
export function armorBonus(item, kind = String(item?.actualKind || item?.kind || '').toLowerCase()) {
    const base = ARMOR_AC_BONUS[kind] ?? item?.a_ac ?? item?.acBonus ?? 0;
    return base + (item?.spe || 0) - Math.min(Math.max(item?.oeroded || 0, item?.oeroded2 || 0), base);
}

export function armorSlot(item) {
    const name = String(item?.actualKind || item?.kind || '').toLowerCase();
    if (/\b(?:cloak|robe|wrapping|mantelet|pall|cape|cope|cloth|smock|apron)\b/.test(name)) return 'cloak';
    if (/\b(?:mail|armor|jacket|coat|dragon scales?)\b/.test(name)) return 'body';
    if (/\bshirt\b/.test(name)) return 'shirt';
    if (/\b(?:helm|helmet|hat|fedora|cornuthaum|cap|pot)\b/.test(name)) return 'helm';
    if (/\b(?:gloves|gauntlets)\b/.test(name)) return 'gloves';
    if (/\b(?:boots|shoes)\b/.test(name)) return 'boots';
    if (/\bshield\b/.test(name)) return 'shield';
    return '';
}
