// Source-derived Terry Pratchett tribute data used by Death and novel paths.
// C refs: dat/tribute, src/do_name.c:noveltitle().

export const TRIBUTE_NOVEL_TITLES = Object.freeze([
    "The Colour of Magic",
    "The Light Fantastic",
    "Equal Rites",
    "Mort",
    "Sourcery",
    "Wyrd Sisters",
    "Pyramids",
    "Guards! Guards!",
    "Eric",
    "Moving Pictures",
    "Reaper Man",
    "Witches Abroad",
    "Small Gods",
    "Lords and Ladies",
    "Men at Arms",
    "Soul Music",
    "Interesting Times",
    "Maskerade",
    "Feet of Clay",
    "Hogfather",
    "Jingo",
    "The Last Continent",
    "Carpe Jugulum",
    "The Fifth Elephant",
    "The Truth",
    "Thief of Time",
    "The Last Hero",
    "The Amazing Maurice and His Educated Rodents",
    "Night Watch",
    "The Wee Free Men",
    "Monstrous Regiment",
    "A Hat Full of Sky",
    "Going Postal",
    "Thud!",
    "Wintersmith",
    "Making Money",
    "Unseen Academicals",
    "I Shall Wear Midnight",
    "Snuff",
    "Raising Steam",
    "The Shepherd's Crown",
]);

export const TRIBUTE_DEATH_QUOTES = Object.freeze([
    "WHERE THE FIRST PRIMAL CELL WAS, THERE WAS I ALSO.  WHERE MAN IS, THERE AM I.  WHEN THE LAST LIFE CRAWLS UNDER FREEZING STARS, THERE WILL I BE.",
    "I AM DEATH, NOT TAXES.  /I/ TURN UP ONLY ONCE.",
    "THINK OF IT MORE AS BEING ... DIMENSIONALLY DISADVANTAGED.",
    "I MAY HAVE ALLOWED MYSELF SOME FLICKER OF EMOTION IN THE RECENT PAST, BUT I CAN GIVE IT UP ANY TIME I LIKE.",
    "HAVE YOU SPOKEN TO RONNIE LATELY?",
    "PLEASE DO NOT PANIC.  YOU ARE MERELY DEAD.",
    "THERE IS A LITTLE CONFUSION AT FIRST.  IT IS ONLY TO BE EXPECTED.",
    "THERE IS ALWAYS TIME FOR ANOTHER LAST MINUTE.",
    "MUSTARD IS ALWAYS TRICKY.",
    "PICKLES OF ALL SORTS DON'T SEEM TO MAKE IT.  I'M SORRY.",
    "IT WON'T HURT A BIT.",
    "SHALL WE GO?",
    "I HAVE COME FOR THEE.",
    "DARK IN HERE, ISN'T IT?",
    "THERE IS NO GOING BACK.  THERE IS NO GOING BACK.",
    "I HAVEN'T GOT ALL DAY, YOU KNOW.",
    "LIFE IS FOR THE LIVING.",
    "NO-ONE EVER WANTED TO TALK TO ME BEFORE.",
    "I HAVEN'T GOT A SINGLE FRIEND.  EVEN CATS FIND ME AMUSING.",
    "YOU'RE ONLY PUTTING OFF THE INEVITABLE.",
    "I SAID WAS.  IT'S CALLED THE PAST TENSE.  YOU'LL SOON GET USED TO IT.",
    "DON'T LET IT UPSET YOU.",
    "I CAN SEE THAT YOU HAVE GOT A LOT TO THINK ABOUT.",
    "PERHAPS IT'S TIME TO CALL IT A DAY.",
    "I KNOW WHEN EVERYONE'S HAD ENOUGH.",
    "I HAVE ALWAYS DONE MY DUTY AS I SAW FIT.",
    "I AM NOT KNOWN FOR MY SENSE OF FUN.",
    "I MEAN THAT THERE IS A TIME FOR EVERYONE TO DIE.",
    "JUST BECAUSE SOMETHING IS A METAPHOR DOESN'T MEAN IT CAN'T BE REAL.",
    "I AM ALWAYS ALONE.  BUT JUST NOW I WANT TO BE ALONE BY MYSELF.",
    "I HAD AN APPOINTMENT WITH YOU TONIGHT.",
]);
