#!/bin/bash
# build-recorder.sh — Build a deterministic NetHack 5.0 "recorder" binary
# from the upstream submodule + the patch series in patches/.
#
# Output: nethack-c/recorder/src/nethack  (the playable binary)
#         nethack-c/recorder-install/games/lib/nethackdir/  (data files)
#
# The recorder produces .session.json files: pinned datetime + seed,
# logged PRNG calls, deterministic 24×80 frame captures. These are
# the same recordings used to score your fork.
#
# You DO NOT need this build to enter the contest. Only build it if
# you want to:
#   - record additional debugging sessions of your own keyplans
#   - audit how the public sessions in sessions/ were produced
#   - cross-check your JS port against C live, side-by-side
#
# Requirements: clang (for cross-platform deterministic argument-eval
# order — gcc's right-to-left would scramble PRNG sequences),
# bison/flex (for the Lua build), make.

set -euo pipefail

OS="$(uname -s)"
case "$OS" in
    Linux)
        HINTS_FILE="sys/unix/hints/linux-minimal"
        LUA_SYSCFLAGS="-DLUA_USE_POSIX"
        NPROC="$(nproc)"
        ;;
    Darwin)
        HINTS_FILE="sys/unix/hints/macosx-minimal"
        LUA_SYSCFLAGS="-DLUA_USE_MACOSX"
        NPROC="$(sysctl -n hw.ncpu)"
        ;;
    *)
        echo "[FAIL] Unsupported OS: $OS" >&2
        exit 1
        ;;
esac

if ! command -v clang &>/dev/null; then
    echo "[FAIL] clang required (deterministic argument evaluation order)" >&2
    exit 1
fi
export CC=clang

PINNED_COMMIT="16ff59115"  # tag NetHack-5.0.0_Release
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
UPSTREAM_DIR="$SCRIPT_DIR/upstream"
RECORDER_DIR="$SCRIPT_DIR/recorder"
INSTALL_PREFIX="$RECORDER_DIR/install"        # inside recorder/, single .gitignore line
PATCHES_DIR="$SCRIPT_DIR/patches"

echo "=== NetHack 5.0 recorder build ==="
echo "    Upstream:   $UPSTREAM_DIR"
echo "    Patches:    $PATCHES_DIR ($(ls $PATCHES_DIR/*.patch 2>/dev/null | wc -l | tr -d ' ') patches)"
echo "    Recorder:   $RECORDER_DIR"
echo "    Install:    $INSTALL_PREFIX"
echo "    Pinned:     $PINNED_COMMIT (NetHack-5.0.0_Release)"
echo

# --- Step 1: ensure upstream NetHack source is present ---
# nethack-c/upstream is registered as a git submodule (see ../.gitmodules
# at the repo root). If your fork didn't init submodules, do so now.
if [ ! -f "$UPSTREAM_DIR/include/patchlevel.h" ]; then
    echo "[step 1] Fetching upstream NetHack source via submodule..."
    cd "$REPO_ROOT"
    git submodule update --init nethack-c/upstream
    if [ ! -f "$UPSTREAM_DIR/include/patchlevel.h" ]; then
        echo "[FAIL] could not populate $UPSTREAM_DIR" >&2
        echo "       try manually: cd $REPO_ROOT && git submodule update --init --recursive" >&2
        exit 1
    fi
fi
VERSION=$(grep -E "VERSION_(MAJOR|MINOR)" "$UPSTREAM_DIR/include/patchlevel.h" | head -2 | awk '{print $3}' | paste -sd. -)
echo "[ok] upstream NetHack $VERSION ready"

# --- Step 2: fresh recorder tree from upstream + patches ---
echo "[step 2] Building recorder tree..."
rm -rf "$RECORDER_DIR"
mkdir -p "$RECORDER_DIR"
# Use rsync to dereference any symlinks and skip git metadata cleanly
rsync -a --exclude='.git' "$UPSTREAM_DIR/" "$RECORDER_DIR/"
# Canonicalize paths (macOS /tmp -> /private/tmp etc.) — git apply's
# safety check refuses paths that traverse a symlink at any depth.
RECORDER_DIR_REAL=$(cd "$RECORDER_DIR" && pwd -P)
cd "$RECORDER_DIR_REAL"
# Initialize a throwaway git repo so `git apply --recount` has an index to
# verify hunks against. Without one, `git apply` silently skips hunks whose
# line counts don't match exactly (the patch series is auto-generated by
# `git diff` and relies on --recount fixups).
git init -q
git -c gc.auto=0 add -A
git -c user.email=build@local -c user.name=build commit -q -m baseline >/dev/null
for p in "$PATCHES_DIR"/*.patch; do
    echo "  applying $(basename $p)..."
    git apply --recount "$p"
done
echo "[ok] $(ls $PATCHES_DIR/*.patch | wc -l | tr -d ' ') patches applied"
rm -rf .git

# --- Step 3: configure (hints + Makefile flags) ---
echo "[step 3] Configuring for $OS..."
cd "$RECORDER_DIR"
case "$OS" in
    Darwin)
        # Upstream NetHack doesn't ship a macOS minimal hints file; use ours.
        cp "$SCRIPT_DIR/macosx-minimal" sys/unix/hints/macosx-minimal
        sed -i.bak "s|__NETHACK_PREFIX__|$INSTALL_PREFIX|g" sys/unix/hints/macosx-minimal
        ;;
    Linux)
        # Upstream ships linux-minimal; just point its PREFIX at our install dir.
        sed -i.bak "s|^\(PREFIX=\).*|\1$INSTALL_PREFIX|" sys/unix/hints/linux-minimal
        ;;
esac
sh sys/unix/setup.sh "$HINTS_FILE"

# --- Step 4: fetch + build Lua (NetHack 5.0 dependency) ---
echo "[step 4] Fetching Lua..."
cd "$RECORDER_DIR"
if [ ! -f lib/lua-5.4.8/src/lua.h ]; then
    make fetch-lua >/dev/null
fi
echo "[step 4] Building Lua..."
( cd lib/lua-5.4.8/src && make CC=clang SYSCFLAGS="$LUA_SYSCFLAGS" a >/dev/null )
mkdir -p lib/lua
cp -f lib/lua-5.4.8/src/liblua.a lib/lua/liblua-5.4.8.a

# --- Step 5: build NetHack ---
echo "[step 5] Building NetHack (parallel -j$NPROC)..."
cd "$RECORDER_DIR"
# Pin BUILD_DATE in the recorder banner. With REPRODUCIBLE_BUILD
# enabled (patch 008), util/makedefs reads SOURCE_DATE_EPOCH and
# uses it as the build clock. 1777723200 = Sat May  2 12:00:00 2026
# UTC = NetHack 5.0.0 release. Override with TELEPORT_BUILD_EPOCH if
# you need a different pin.
export SOURCE_DATE_EPOCH="${TELEPORT_BUILD_EPOCH:-1777723200}"
make -j"$NPROC" SYSCFLAGS="$LUA_SYSCFLAGS" >/dev/null
make install >/dev/null
echo
echo "[ok] recorder built: $RECORDER_DIR/src/nethack"
echo "[ok] installed to:    $INSTALL_PREFIX/games/lib/nethackdir/"
echo
echo "Try recording a session:"
echo "  NETHACK_SEED=8000 NETHACK_FIXED_DATETIME=20260502143000 \\"
echo "    NETHACK_RNGLOG=/tmp/rng.log \\"
echo "    $INSTALL_PREFIX/games/lib/nethackdir/nethack"
